export const FETCH_CLIENT_LIST_ACTION = 'FETCH_CLIENT_LIST_ACTION';
export const FETCH_CLIENT_PROFILE_ACTION = 'FETCH_CLIENT_PROFILE_ACTION';
export const FETCH_TOTAL_CLIENTS_ACTION = 'FETCH_TOTAL_CLIENTS_ACTION';

export const EXPIRED_FILTER = 'expired';
export const ACTIVE_FILTER = 'active';
export const NAME_FILTER = 'name';