version: '3.1'
services:
  server:
    container_name: nutrilog-server
    build:
      dockerfile: Dockerfile.dev
      context: ./nutrilog
    volumes:
      - /nutrilog/node_modules
      - ./nutrilog:/nutrilog
    ports:
      - '5000:5000'
    depends_on:
      - postgres
  postgres:
    container_name: nutrilog-postgres-dev-db
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: nutrilog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres